# information about the source library
source:
  github:
    user: geoscixyz
    repo: geosci-labs
    branch: master

# setup options for the library
setup:
  environment: environment.yml  # include the environment.yml from the source
  requirements: requirements.txt  # include the requirements.txt file
  include_tests: True  # create tests
  # index_notebook: True  # create a template index notebook - Not implemented yet

# library configuration
library:
  - source: notebooks/dcip
    target: notebooks/dcip
    include:
      - [DCIP_2D_Overburden_Pseudosections.ipynb, dcip_2d_overburden.ipynb]  # the second item in the list indicates that you want to rename the file
      - DC_Building_Pseudosections.ipynb

  - source: notebooks/em
    target: notebooks/em
    include:
      - EM_Pipeline.ipynb

  - source: notebooks/mag
    target: notebooks/mag
    include: all


